Update plugin-ci-workflow.yml

diff --git a/.github/workflows/plugin-ci-workflow.yml b/.github/workflows/plugin-ci-workflow.yml
--- a/.github/workflows/plugin-ci-workflow.yml
+++ b/.github/workflows/plugin-ci-workflow.yml
@@ -176,6 +176,10 @@ jobs:
       run: |
         cd ${{ github.workspace }}/cacti/plugins/thold
         sudo php cli_import.php --filename=.github/workflows/thold_sample_data.xml
+        if [ $? -ne 0 ]; then
+          echo "Failed to import Thold sample data"
+          exit 1
+        fi
     
     - name: Check PHP Syntax for Plugin
       run: |
